### ISSUE TITLE
Quotes no longer being fetched.

### ISSUE THREAD

**Issue by BadOPCode** [PirtleShell/owl-wisdom#3]
BrainyQuote.com has changed their HTML which is breaking anyone who is attempting to use HTML scraping to get the quotes.  HTML scrapping is more trouble than it's worth when they provide an XML RSS feed for their quotes.  Switching it to RSS will save on the frustration of trying to track where the quote is today.

I have made a PR that addresses this issue https://github.com/pirtleshell/owl-wisdom/pull/2
Please take a look when you have a chance.

**Comment by pirtleshell** [comment]
Sorry for the delay! Thanks for the PR
